{% set version = "2.3-5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-prabclus
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/prabclus_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/prabclus/prabclus_{{ version }}.tar.gz
  sha256: ead9132babe7551a7c480c19e0ebead10a6320baeef3b0e10ed66e3cbbd64e8b

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-mclust
  run:
    - r-base
    - r-mass
    - r-mclust

test:
  commands:
    - $R -e "library('prabclus')"           # [not win]
    - "\"%R%\" -e \"library('prabclus')\""  # [win]

about:
  home: https://www.unibo.it/sitoweb/christian.hennig/en/
  license: GPL
  summary: 'Distance-based parametric bootstrap tests for clustering with  spatial neighborhood information. Some distance measures,  Clustering of presence-absence, abundance and multilocus genetical data  for species delimitation, nearest neighbor  based noise detection. Genetic distances between communities. Tests whether
    various distance-based regressions are equal. Try package?prabclus for on overview. '
  license_family: GPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: prabclus
# Title: Functions for Clustering and Testing of Presence-Absence, Abundance and Multilocus Genetic Data
# Version: 2.3-1
# Date: 2019-06-03
# Author: Christian Hennig <christian.hennig@unibo.it>,  Bernhard Hausdorf <Hausdorf@zoologie.uni-hamburg.de>
# Depends: R (>= 2.10), MASS, mclust
# Suggests: spdep, spatialreg, bootstrap, maptools, foreign, mvtnorm
# Description: Distance-based parametric bootstrap tests for clustering with  spatial neighborhood information. Some distance measures,  Clustering of presence-absence, abundance and multilocus genetical data  for species delimitation, nearest neighbor  based noise detection. Genetic distances between communities. Tests whether various distance-based regressions are equal. Try package?prabclus for on overview.
# Maintainer: Christian Hennig <christian.hennig@unibo.it>
# License: GPL
# URL: https://www.unibo.it/sitoweb/christian.hennig/en/
# NeedsCompilation: no
# Packaged: 2019-06-04 16:07:54 UTC; christian_hennig
# Repository: CRAN
# Date/Publication: 2019-06-04 21:50:03 UTC
