{% set version = '2.2-7' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-prabclus
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/prabclus_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/prabclus/prabclus_{{ version }}.tar.gz
  sha256: eb06fdccca73eabbbc1f0119a6c1c09e9ae6a659cf9a2bb483f5889811ad5640

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-mclust
  run:
    - r-base
    - r-mass
    - r-mclust

test:
  commands:
    - $R -e "library('prabclus')"           # [not win]
    - "\"%R%\" -e \"library('prabclus')\""  # [win]

about:
  home: http://www.homepages.ucl.ac.uk/~ucakche
  license: GPL
  summary: 'Distance-based parametric bootstrap tests for clustering with  spatial neighborhood
    information. Some distance measures,  Clustering of presence-absence, abundance
    and multilocus genetical data  for species delimitation, nearest neighbor  based
    noise detection. Try package?prabclus for on overview. '
  license_family: GPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: prabclus
# Title: Functions for Clustering of Presence-Absence, Abundance and Multilocus Genetic Data
# Version: 2.2-7
# Date: 2019-01-16
# Author: Christian Hennig <christian.hennig@unibo.it>,  Bernhard Hausdorf <Hausdorf@zoologie.uni-hamburg.de>
# Depends: R (>= 2.10), MASS, mclust
# Suggests: spdep, maptools, foreign, mvtnorm
# Description: Distance-based parametric bootstrap tests for clustering with  spatial neighborhood information. Some distance measures,  Clustering of presence-absence, abundance and multilocus genetical data  for species delimitation, nearest neighbor  based noise detection. Try package?prabclus for on overview.
# Maintainer: Christian Hennig <christian.hennig@unibo.it>
# License: GPL
# URL: http://www.homepages.ucl.ac.uk/~ucakche
# NeedsCompilation: no
# Packaged: 2019-01-16 19:11:50 UTC; christian_hennig
# Repository: CRAN
# Date/Publication: 2019-01-17 13:40:07 UTC
