appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: qfGx385+foR7BRpTvT8ctIKJHgWjF3A26onPW9IWh/QQWM5xwr81jH7ypBNkGbPYAjjq002VXN/+2Wlfh5vHhS1TP03uGHWVQRujxz/zPZwRn4mz1f6ygQFO+gV21pk0qcekMbyb3r+MLtaY5sewomHlEdMYcaPJPSSpwu9qeZffRQJ4simJCMoz9O6bpWhHi2H/1lK8KxOp1IJXSVR7RxxOH4FVmW6qr8yuPqltFphyQKJ237wkHgfck9XZYBw9Y04F09E11Pcw6C3cP4jZGoENKUeAMJIBF3Sb0up9OwgrLSwFoMtaddvaJnCJOlZYGmNLowPfCH8XCCG4eCzBlfoLW5fdwn5oqyS7h865QIAFGYGZNPXdMEKsQMblRjE28JhwN/FGslzEpcKrA1qaVeDbt2j+oTyRSzMhMSIdshwhAXbjjXuhppWf0MpE/ER8ZB5a3WJNu+3ngxIBYxdIZFqCFSlOX5ZX26BfG4QAMFVlS3lmh7gGLCItN7Q1Su1rhGHO35miHG6kajnnaFh9Bkab/GQZELOeGsOFNA6ucCTXHl19QJGT3jNyHVget7RX5b5uGo47o7+lwmaAiEfL9ifo3+Fs7l/ITRszi9zD4PZXzfegs1Z5win26HWgXTb/V1Ryh+EIZlvuOQykDQ/hdapFdNa+/DX72q7Cdomv9D0=}
